
# Datos para el Dyploid

spring.application.name=MundoLaptopBackend
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ndeprtuzdybblzzydqrt
spring.datasource.password=bt&S8@L-ktY@yLK
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=clave-secreta-larga-de-al-menos-32-caracteres-MundoLaptopBD-2026
jwt.expiration=86400000

#Contraseña: bt&S8@L-ktY@yLK
#Url completa: postgresql://postgres.ndeprtuzdybblzzydqrt:[YOUR-PASSWORD]@aws-0-us-west-2.pooler.supabase.com:5432/postgres


spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
