spring.application.name=MundoLaptopBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/MundoLaptopBD
spring.datasource.username=postgres
spring.datasource.password=PWEc6GZ
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=clave-secreta-larga-de-al-menos-32-caracteres-MundoLaptopBD-2026

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
